config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ecmwf-projects/infero:
      branch: master
      repo: https://github.com/ecmwf-projects/infero
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ecmwf-projects/infero git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-carmine-tarantula.sh
        container: qc.acc_crabby-wisteria-burmese
  QC.Doc:
    repos:
      github.com/ecmwf-projects/infero find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-cerulean-beagle.sh
        container: qc.doc_cloudy-platinum-fly
      github.com/ecmwf-projects/infero git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-chocolate-malamute.sh
        container: qc.doc_crappy-viridian-donkey
      github.com/ecmwf-projects/infero markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-wheat-dane.sh
        container: qc.doc_gloppy-violet-barnacle
      github.com/ecmwf-projects/infero restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cerulean-wasp.sh
        container: qc.doc_dorky-dandelion-owl
  QC.Lic:
    repos:
      github.com/ecmwf-projects/infero licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-sangria-tortoise.sh
        container: qc.lic_breezy-bronze-barnacle
  QC.Sec:
    repos:
      github.com/ecmwf-projects/infero bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-corn-avocet.sh
        container: qc.sec_wiggy-scarlet-peccary
  QC.Sty:
    repos:
      github.com/ecmwf-projects/infero flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-tan-stingray.sh
        container: qc.sty_dorky-xanthic-tapir
  QC.Ver:
    repos:
      github.com/ecmwf-projects/infero get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-tangerine-zebra.sh
        container: qc.ver_smelly-heliotrope-kingfisher
timeout: 5400
