config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ecmwf-projects/infero:
      branch: master
      repo: https://github.com/ecmwf-projects/infero
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ecmwf-projects/infero git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-salmon-starfish.sh
        container: qc.acc_bluesy-cinnabar-gorilla
  QC.Doc:
    repos:
      github.com/ecmwf-projects/infero find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-periwinkle-reindeer.sh
        container: qc.doc_silly-firebrick-ocelot
      github.com/ecmwf-projects/infero git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-champagne-leopard.sh
        container: qc.doc_tasty-purple-shark
      github.com/ecmwf-projects/infero markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cinnamon-retriever.sh
        container: qc.doc_pasty-rust-stingray
      github.com/ecmwf-projects/infero restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-orchid-caiman.sh
        container: qc.doc_grumpy-cinnamon-ladybird
  QC.Lic:
    repos:
      github.com/ecmwf-projects/infero licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-asparagus-crane.sh
        container: qc.lic_droopy-platinum-gorilla
  QC.Sec:
    repos:
      github.com/ecmwf-projects/infero bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-olive-ragdoll.sh
        container: qc.sec_wiggy-orange-armadillo
  QC.Sty:
    repos:
      github.com/ecmwf-projects/infero flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-green-ferret.sh
        container: qc.sty_boozy-aqua-frog
  QC.Ver:
    repos:
      github.com/ecmwf-projects/infero get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-linen-burmese.sh
        container: qc.ver_beady-sapphire-chinook
timeout: 5400
